### ISSUE TITLE
Ann - Checksum strategy, make sure we understand the checksums needed for GCP and AWS

### ISSUE THREAD

**Issue by teresa-barsanti** [NimbusInformatics/bdcat-ingest-prototype#3]

**Comment by briandoconnor** [comment]
- AWS is working correctly... multi-part of not... all looks good
- Google checksum looks correct, but she's still testing
- she's working on the code to do threading now

**Comment by xavanx** [comment]
For google, crc32c checksum is calculated and added to the upload details. google rejects if after upload, checksums are different. This has been verified to work. for aws, a modified md5sum hash checksum is made of the parts, and the script compares md5sum values. This is confirmed to work too.
